name: Update color scripts

on:
  workflow_dispatch:
  schedule:
    - cron: "50 1 * * *"

jobs:
  update:
    name: Color scripts update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout builder
        uses: actions/checkout@v2
        with:
          repository: InspectorMustache/base16-builder-python
      - name: Checkout template
        uses: actions/checkout@v2
        with:
          path: templates/mate-terminal
      - name: Update builder
        run: |
          sudo apt-get install python3-aiofiles python3-pystache
          python3 pybase16.py update
      - name: Build
        run: |
          python3 pybase16.py build -t mate-terminal
          chmod +x output/mate-terminal/color-scripts/base16-*.sh
          mkdir -p templates/mate-terminal/color-scripts
          cp output/mate-terminal/color-scripts/base16-*.sh templates/mate-terminal/color-scripts
      - name: Commit color scripts
        run: |
          cd templates/mate-terminal
          git add color-scripts
          if ! git diff --staged --exit-code >/dev/null; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -m "Updated color scripts"
            git push
          fi
